# Generated by Django 5.0.3 on 2024-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_books_title_alter_books_user_alter_complain_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community'),
        ),
    ]
