# Generated by Django 5.0.3 on 2024-05-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_communityform_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='titel',
            new_name='title',
        ),
    ]
